#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

docker run --rm \
    -v "$PROJECT_DIR:/app" \
    -w /app/tests \
    --network tests_default \
    -e DB_HOST=mysql \
    -e DB_PORT=3306 \
    reg.localbin.dev/neuedev/core/docker/php-dev:8.3 \
    php vendor/phpunit/phpunit/phpunit "$@"
